import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as THREE from 'three';
import {FILM_DURATION,FILM_SEGMENTS,FILM_IMPACTS,sourceAt,filmAt,filmState,cutAt} from '../src/director-cut.js';
import {Fighter} from '../src/figure.js';import {TRANSFER} from '../src/weapon-transfer.js';import {STORY} from '../src/narrative.js';
import {ASSAULT_BEATS} from '../src/weapon-transfer.js';
test('the director cut is exactly 90 seconds with seven non-repeated editorial sections',()=>{assert.equal(FILM_DURATION,90);assert.equal(FILM_SEGMENTS.length,7);let end=0,previousSource=-1;for(const s of FILM_SEGMENTS){assert.ok(Math.abs(s.start-end)<1e-8);assert.ok(s.sourceIn>previousSource);assert.ok(s.sourceOut>s.sourceIn);end=s.end;previousSource=s.sourceOut;}assert.equal(end,90);assert.equal(sourceAt(90),165);});
test('a full playback contains exactly one shared jump-back and one shared forward dash',()=>{for(const reason of [/BACKWARD LEAP/,/FORWARD DASH/]){let previous=false,runs=0;for(let t=0;t<90;t+=.01){const state=filmState(t),active=state.fighters.every(f=>reason.test(f.flightIntent||''));if(active&&!previous)runs++;previous=active;}assert.equal(runs,1,String(reason));}for(const t of [72.5,73.45,120.5,121.45])assert.equal(filmAt(t),null,'repeated act dash must be cut, not hidden in another camera shot');});
test('critical story events survive exactly once and remain causally ordered',()=>{const times=[67.142857,89.285714,STORY.split,TRANSFER.launch,TRANSFER.catch,...STORY.cuts,STORY.toss,STORY.extinguish,159].map(filmAt);times.forEach((t,i)=>{assert.ok(t!==null);if(i)assert.ok(t>times[i-1]);});assert.ok(FILM_IMPACTS.length<350);assert.ok(FILM_IMPACTS.length>200);});
test('film-time scrubbing is monotone and chooses deliberate camera cuts at edit boundaries',()=>{let previous=-1;for(let t=0;t<90;t+=.01){const source=sourceAt(t);assert.ok(source>previous);previous=source;}for(const s of FILM_SEGMENTS){assert.equal(cutAt(s.start).index,s.index);assert.ok(Math.abs(sourceAt(s.start)-s.sourceIn)<1e-6);assert.ok(Math.abs(filmAt(s.sourceIn)-s.start)<1e-6);}});
test('the 90-second film keeps anatomical limits, fixed bones and grounded feet',()=>{const scene=new THREE.Scene(),f=[new Fighter(scene,0),new Fighter(scene,1)];f[0].equipOffhand(f[1].saber);let samples=0;for(let t=0;t<90;t+=.025){const s=filmState(t);samples++;f.forEach((a,i)=>{a.update(s.fighters[i],s.contact,s.lock,s.sourceTime);assert.ok(a.anatomy.gripError<.003);for(const angle of a.anatomy.armFlex)assert.ok(angle>=9.999&&angle<=145.001);for(const [upper,lower]of a.anatomy.armLengths){assert.ok(Math.abs(upper-.405)<1e-8);assert.ok(Math.abs(lower-.39)<1e-8);}if(s.fighters[i].y<.035)for(const foot of a.anatomy.footWorld)assert.ok(foot[1]>=.039);});}assert.equal(samples,3600);});
test('pressure and final assault travel across the platform instead of prolonged sparring at one spot',()=>{const center=t=>{const f=filmState(t).fighters;return(f[0].x+f[1].x)*.5;};assert.ok(Math.abs(center(30)-center(35))>1.4);const end=filmAt(151.4),start=filmAt(145.6);assert.ok(end!==null&&start!==null);assert.ok(Math.abs(center(end)-center(start))>1.7);});
test('the local music edit is supplied while the original soundtrack remains intact',()=>{assert.ok(fs.statSync('public/audio/jedi-experiment-90s.mp3').size>1e6);assert.ok(fs.statSync('public/audio/jedi-experiment.mp3').size>5e6);const cut=JSON.parse(fs.readFileSync('src/director-cut.json'));assert.equal(cut.duration_seconds,90);assert.match(cut.method,/original pitch and tempo/);});

test('post-catch paired cuts ramp from roughly five to nine strikes per film second without speeding up the music',()=>{
  const beats=ASSAULT_BEATS.map(filmAt).filter(t=>t!==null),gaps=beats.slice(1).map((t,i)=>t-beats[i]).filter(dt=>dt<.5);
  assert.ok(beats.length>=125);assert.ok(gaps[0]<.23&&gaps[0]>.18);assert.ok(gaps.at(-1)<.12&&gaps.at(-1)>.09);
  const cut=JSON.parse(fs.readFileSync('src/director-cut.json'));assert.deepEqual(cut.cues,[{authored:0,music:0},{authored:90,music:90}]);
});
