import fs from 'node:fs';import path from 'node:path';
import {parseUsage,developmentTime,PRICE_SOURCE,PRICE_VERIFIED} from '../src/accounting.js';
export const root=path.resolve(import.meta.dirname,'..');
export function refreshUsage(){
  const session=process.env.CODEX_THREAD_ID||'01a106bb-f519-75a0-9bcd-f930fd76c48e';
  const dir=path.join(process.env.CODEX_HOME||path.join(process.env.HOME,'.codex'),'sessions','2026','10','04');
  const name=fs.readdirSync(dir).find(f=>f.endsWith('-'+session+'.jsonl'));if(!name)throw Error('No measured session log found. Tokens will not be fabricated.');
  const rows=fs.readFileSync(path.join(dir,name),'utf8').split('\n').filter(Boolean).flatMap(l=>{try{return[JSON.parse(l)]}catch{return[]}}),asOf=new Date().toISOString();
  const report={session_id:session,recorded_at:asOf,...parseUsage(rows),development_time:developmentTime(rows,asOf),pricing_source:PRICE_SOURCE,pricing_verified_on:PRICE_VERIFIED,pricing_basis:'Standard API-equivalent, not actual subscription billing',rates_per_million:{short:{input:2,cached:.1,write:2.5,output:10},long:{input:4,cached:.2,write:5,output:15},long_context_threshold:272000},fast_mode_equivalent_multiplier:2,is_invoice:false,external_asset_generation:false,runtime_paid_api_calls:0,notes:['Cumulative input includes repeated context. Cached and cache-write tokens are billed subsets, not added to input.','Reasoning is a subset of output and is not charged twice.','Deduplicated cumulative usage events; snapshot excludes the current in-flight model response.','No subagents were used. Hidden review/tool billing is not metered and is excluded, not assumed free.','Only counters from this exact experiment session are read. Standard equivalent is used because service tier is not recorded.']};
  for(const dir of ['progress','public/progress']){fs.mkdirSync(path.join(root,dir),{recursive:true});fs.writeFileSync(path.join(root,dir,'usage.json'),JSON.stringify(report,null,2)+'\n');}
  const t=report.tokens,d=report.development_time;
  fs.writeFileSync(path.join(root,'progress','COST.md'),`# Eclipse · experiment 003\n\nMeasured as of ${report.usage_as_of} UTC. Snapshot: ${asOf}.\n\nModel: **${report.model}** · effort: **${report.reasoning_effort}** · service tier: ${report.recorded_service_tier}.\n\n| Metric | Value |\n|---|---:|\n| Elapsed development | ${(d.elapsed_seconds/60).toFixed(2)} minutes |\n| Logged active time | ${(d.active_seconds/60).toFixed(2)} minutes |\n| Input | ${t.input_tokens.toLocaleString()} |\n| Cached input, subset | ${t.cached_input_tokens.toLocaleString()} |\n| Cache writes, subset | ${(t.cache_write_input_tokens||0).toLocaleString()} |\n| Uncached input | ${(t.input_tokens-t.cached_input_tokens-(t.cache_write_input_tokens||0)).toLocaleString()} |\n| Output, including reasoning | ${t.output_tokens.toLocaleString()} |\n| Reasoning, subset | ${t.reasoning_output_tokens.toLocaleString()} |\n| Input + output | ${t.total_tokens.toLocaleString()} |\n| Standard API-equivalent | $${report.api_equivalent_usd.toFixed(6)} USD |\n| Fast API-equivalent, if selected | $${(report.api_equivalent_usd*2).toFixed(6)} USD |\n\n**API-equivalent estimate, not an invoice or subscription charge.** Verified October 4, 2026 from [official OpenAI pricing](${PRICE_SOURCE}) and [model notes](https://developers.openai.com/api/docs/models/gpt-6.1-sol). Standard short-context rates per million: $2 uncached input, $0.10 cached input, $2.50 cache writes, $10 output. Above 272,000 input tokens per request: $4 / $0.20 / $5 / $15. Each request is priced independently.\n\n${d.method}\n\n${report.notes.map(n=>'- '+n).join('\n')}\n\nThe experiment uses procedural assets and no paid runtime API calls. Refresh with \`npm run usage\`.\n`);
  return report;
}
if(process.argv[1]===import.meta.filename){const r=refreshUsage();console.log(JSON.stringify({model:r.model,tokens:r.tokens,api_equivalent_usd:r.api_equivalent_usd,elapsed_minutes:r.development_time.elapsed_seconds/60,usage_as_of:r.usage_as_of}));}
