import * as THREE from 'three';
export const GROUND_IMPACTS=[26.428571,74.428571,122.428571,127.32,144.285714];
export function weatheredSurface(scene){
  let seed=4821;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  // A fissure is a recess, not a pale, lit decal laid over the puddle.
  const fissureMat=new THREE.MeshBasicMaterial({color:'#020504'}),edgeMat=new THREE.LineBasicMaterial({color:'#64716a',transparent:true,opacity:.14});
  function crackPath(start,angle,length){const points=[start.clone()];for(let j=1;j<=12;j++){angle+=(rnd()-.5)*.55;const prev=points.at(-1);points.push(new THREE.Vector3(prev.x+Math.cos(angle)*length/12,.053,prev.z+Math.sin(angle)*length/12));}return points;}
  function crackMesh(paths,width){const vertices=[],edges=[];for(const path of paths)for(let j=0;j<path.length-1;j++){const a=path[j],b=path[j+1],dx=b.x-a.x,dz=b.z-a.z,n=Math.hypot(dx,dz)||1,w=width*(.45+rnd());const ax=a.x-dz/n*w,az=a.z+dx/n*w,bx=b.x-dz/n*w,bz=b.z+dx/n*w;vertices.push(ax,.052,az,bx,.052,bz,b.x,.052,b.z,ax,.052,az,b.x,.052,b.z,a.x,.052,a.z);edges.push(ax,.055,az,bx,.055,bz);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.computeVertexNormals();const group=new THREE.Group();group.add(new THREE.Mesh(g,fissureMat));const e=new THREE.BufferGeometry();e.setAttribute('position',new THREE.Float32BufferAttribute(edges,3));group.add(new THREE.LineSegments(e,edgeMat));return group;}
  const base=[];for(let i=0;i<32;i++){const a=rnd()*6.283,r=Math.sqrt(rnd())*5.8;base.push(crackPath(new THREE.Vector3(Math.cos(a)*r,.05,Math.sin(a)*r),rnd()*6.283,.35+rnd()*1.6));}scene.add(crackMesh(base,.018));
  const scuffGeo=new THREE.CircleGeometry(1,7),scuffMat=new THREE.MeshStandardMaterial({color:'#111918',metalness:.01,roughness:.94});const scuffs=new THREE.InstancedMesh(scuffGeo,scuffMat,80),dummy=new THREE.Object3D();for(let i=0;i<80;i++){const a=rnd()*6.283,r=Math.sqrt(rnd())*6.8;dummy.position.set(Math.cos(a)*r,.047,Math.sin(a)*r);dummy.rotation.x=-Math.PI/2;dummy.rotation.z=rnd()*6.283;dummy.scale.set(.015+rnd()*.10,.007+rnd()*.025,1);dummy.updateMatrix();scuffs.setMatrixAt(i,dummy.matrix);}scene.add(scuffs);
  const fractures=GROUND_IMPACTS.map((at,index)=>{const paths=[],origins=[[0,0],[-.75,.35],[.45,-.55],[.2,.65],[-.4,-.25]],origin=origins[index];for(let ray=0;ray<5;ray++){const a=ray/5*6.283+(rnd()-.5)*.5,main=crackPath(new THREE.Vector3(...[origin[0],.053,origin[1]]),a,1.4+rnd()*2.0);paths.push(main);for(const j of [4,8])paths.push(crackPath(main[j],a+(rnd()<.5?-1:1)*.7,.3+rnd()*.7));}const group=crackMesh(paths,.016+index*.001);scene.add(group);group.visible=false;return{at,group};});
  const shock=new THREE.Mesh(new THREE.TorusGeometry(1,.009,5,96),new THREE.MeshBasicMaterial({color:'#b2c3b5',transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}));shock.rotation.x=Math.PI/2;shock.position.y=.08;scene.add(shock);
  const shards=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.08,0),new THREE.MeshStandardMaterial({color:'#586260',roughness:.8}),38);shards.castShadow=true;scene.add(shards);
  return{fractures,update(t){for(const f of fractures){f.group.visible=t>=f.at;f.group.scale.setScalar(Math.max(.0001,Math.min(1,(t-f.at)*3.4)));}const at=GROUND_IMPACTS.findLast(x=>t>=x)??-100,age=t-at;shock.scale.setScalar(1+age*10);shock.material.opacity=age<.4?(1-age/.4)*.34:0;for(let i=0;i<38;i++){const a=i*2.3999,v=1.8+(i%7)*.26,dt=Math.min(age,.72);dummy.position.set(Math.cos(a)*v*dt,Math.max(.06,.1+(2.0+(i%5)*.22)*dt-4.9*dt*dt),Math.sin(a)*v*dt);dummy.rotation.set(dt*3+i,dt*5+i,dt*2);dummy.scale.setScalar(age<1.5?1:0);dummy.updateMatrix();shards.setMatrixAt(i,dummy.matrix);}shards.instanceMatrix.needsUpdate=true;}};
}
