import * as THREE from 'three';
export function createWeather(scene){
  let seed=8471;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  const n=3500,p=new Float32Array(n*6),speed=new Float32Array(n*2);
  for(let i=0;i<n;i++){const x=(rnd()-.5)*32,y=rnd()*20,z=(rnd()-.5)*32;p.set([x,y,z,x-.07,y+.4+rnd()*.28,z+.015],i*6);speed[i*2]=speed[i*2+1]=18+rnd()*7;}
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(p,3));geo.setAttribute('speed',new THREE.BufferAttribute(speed,1));
  const rainMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{time:{value:0}},vertexShader:'attribute float speed;uniform float time;varying float depth;void main(){vec3 p=position;p.y=mod(p.y-time*speed,20.);p.x+=sin(time*.6)*.2;vec4 v=modelViewMatrix*vec4(p,1.);depth=length(v.xyz);gl_Position=projectionMatrix*v;}',fragmentShader:'varying float depth;void main(){float a=.33*exp(-depth*.04);gl_FragColor=vec4(.48,.61,.67,a);}'});const rain=new THREE.LineSegments(geo,rainMat);rain.frustumCulled=false;scene.add(rain);
  const count=520,seeds=new Float32Array(count),rippleGeo=new THREE.PlaneGeometry(1,1);const rippleMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{time:{value:0}},vertexShader:'attribute float phase;varying vec2 vUv;varying float vPhase;void main(){vUv=uv;vPhase=phase;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.);}',fragmentShader:'uniform float time;varying vec2 vUv;varying float vPhase;void main(){float age=fract(time*1.9+vPhase);float r=length(vUv-.5)*2.;float ring=exp(-pow((r-age)/.034,2.));float inner=exp(-pow((r-age*.61)/.025,2.))*.3;float a=(ring+inner)*pow(1.-age,2.)*.22;gl_FragColor=vec4(.5,.62,.65,a);}'});
  const ripples=new THREE.InstancedMesh(rippleGeo,rippleMat,count),dummy=new THREE.Object3D();for(let i=0;i<count;i++){const a=rnd()*Math.PI*2,r=Math.sqrt(rnd())*7.0;dummy.position.set(Math.cos(a)*r,.048,Math.sin(a)*r);dummy.rotation.x=-Math.PI/2;dummy.scale.setScalar(.17+rnd()*.27);dummy.updateMatrix();ripples.setMatrixAt(i,dummy.matrix);seeds[i]=rnd();}rippleGeo.setAttribute('phase',new THREE.InstancedBufferAttribute(seeds,1));scene.add(ripples);
  const splashN=900,sp=new Float32Array(splashN*3),phase=new Float32Array(splashN);for(let i=0;i<splashN;i++){const a=rnd()*6.283,r=Math.sqrt(rnd())*8.4;sp.set([Math.cos(a)*r,.05,Math.sin(a)*r],i*3);phase[i]=rnd();}
  const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(sp,3));sg.setAttribute('phase',new THREE.BufferAttribute(phase,1));const sm=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{time:{value:0}},vertexShader:'attribute float phase;uniform float time;varying float alpha;void main(){float age=fract(time*2.3+phase);vec3 p=position;p.y+=sin(age*3.14159)*.065;p.x+=sin(phase*66.)*age*.045;alpha=pow(1.-age,2.);vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(28./-mv.z,1.,4.);}',fragmentShader:'varying float alpha;void main(){float d=length(gl_PointCoord-.5)*2.;gl_FragColor=vec4(.6,.75,.8,exp(-d*d*5.)*alpha*.35);}'});scene.add(new THREE.Points(sg,sm));
  const forceUniforms={forceFrom:{value:new THREE.Vector3()},forceTo:{value:new THREE.Vector3()},forcePower:{value:0}};
  for(const [mat,world]of [[rainMat,'modelMatrix*vec4(p,1.)'],[rippleMat,'modelMatrix*instanceMatrix*vec4(position,1.)'],[sm,'modelMatrix*vec4(p,1.)']]){
    Object.assign(mat.uniforms,forceUniforms);mat.vertexShader='varying vec3 forceWorld;\n'+mat.vertexShader.replace('gl_Position=',`forceWorld=(${world}).xyz;gl_Position=`);
    mat.fragmentShader='uniform vec3 forceFrom;uniform vec3 forceTo;uniform float forcePower;varying vec3 forceWorld;\n'+mat.fragmentShader.replace(/}\s*$/,`vec3 fd=forceTo-forceFrom;float fu=clamp(dot(forceWorld-forceFrom,fd)/max(.001,dot(fd,fd)),0.,1.);float glow=exp(-length(forceWorld-(forceFrom+fu*fd))*1.8)*forcePower;gl_FragColor.rgb+=vec3(.22,.27,.85)*glow*1.8;gl_FragColor.a*=1.+glow*.35;}`);
  }
  return{illuminateForce(from,to,intensity){forceUniforms.forceFrom.value.copy(from);forceUniforms.forceTo.value.copy(to);forceUniforms.forcePower.value=intensity;},update(t){rainMat.uniforms.time.value=t;rippleMat.uniforms.time.value=t;sm.uniforms.time.value=t;},counts:{rainStreaks:n,groundRipples:count,groundSplashes:splashN}};
}
